### ISSUE TITLE
[Improvement] Remove selected cell highlight 

### ISSUE THREAD

**Issue by BetimBeja** [iTanzhao/EntityAccessManagement#2]
Currently the selected cell is highlighted but this info does not give any added value to the tool, and it doesn't look nice (for my personal taste)
![image](https://user-images.githubusercontent.com/11160171/158570933-588c80d0-316c-4b3b-9409-6d972e399250.png)

You could set the default cell style to not differentiate cells from selected state.
![image](https://user-images.githubusercontent.com/11160171/158570785-b5854908-aabc-4d02-8b7c-e9e2cb19c6f4.png)

**Comment by iTanzhao** [comment]
Hi @BetimBeja ，
Thank you very much for your attention and suggestions, I will continue to optimize the UI and fix bugs.
