### ISSUE TITLE
Latest version does not match assembly version and Nuget package version

### ISSUE THREAD

**Issue by MscrmTools** [iTanzhao/EntityAccessManagement#5]
This results in your tool always marked as updatable.

Please make sure Assembly version and the Nuget package have the same version

![image](https://user-images.githubusercontent.com/10774317/217045233-8360b11c-4936-4476-9a20-266b02854cbc.png)

**Comment by iTanzhao** [comment]
I have modified it, please check .

**Comment by MscrmTools** [comment]
Seems ok to me!
Thank you for fixing @iTanzhao
